###########
# site.url, site.title

url:   'http://planetbeer.github.io'
title: 'Planet Beer'

########
# more settings

markdown: kramdown

collections:
  links:
    output: true

sass:
  sass_dir: css
  style:    expanded



exclude:
- README.md
- _data/books/README.md


safe: true
lsi: false

